[package]
name = "gruid-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "UI widgets for gruid: menu, pager, text input, label, styled text"

[dependencies]
gruid-core = { workspace = true }
