[package]
name = "gruid-crossterm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Crossterm backend for gruid"

[dependencies]
gruid-core = { workspace = true }
crossterm = { workspace = true }
